import Shell from '../../components/Shell';
import styles from '../legal/legal.module.css';

export const metadata = { title: 'Privacy Policy | GENEVIEVE Grey Nomads' };

export default function PrivacyPage() {
  return (
    <Shell current="My Trip">
      <article className={`panel ${styles.card}`}>
        <p className="eyebrow">GENEVIEVE Grey Nomads</p><h2>Privacy Policy</h2>
        <p className={styles.meta}>Last updated: 19 August 2026</p>
        <p>This Privacy Policy explains how Tracey Ann Kennedy trading as GENEVIEVE App™, ABN 36 530 564 761, handles personal information for GENEVIEVE Grey Nomads. We aim to manage personal information consistently with Australian privacy requirements that apply to us, including the Australian Privacy Principles where applicable.</p>

        <h3>1. Information we collect</h3>
        <ul><li>A randomly generated device identifier used to associate saved trips and membership with your device.</li><li>Trip information you choose to save, such as origin, destination, budget, distance and planning settings.</li><li>Subscription information received from Stripe, such as billing email, Stripe customer/subscription identifiers, subscription status and payment outcome.</li><li>Support messages and contact information you choose to provide.</li><li>Technical information generated by hosting and security systems, which may include IP address, browser/device information, timestamps and request logs.</li></ul>
        <p>The current Around Me feature uses browser geolocation to create a nearby map search. This build does not intentionally persist your precise current latitude and longitude in the GENEVIEVE trip database.</p>

        <h3>2. Payment information</h3>
        <p>Full payment-card details are entered into Stripe-hosted payment pages and are not stored in the GENEVIEVE Neon database. Stripe processes those details under its own privacy and security obligations.</p>

        <h3>3. Why we use information</h3>
        <p>We use personal information to provide and save journeys, operate membership, process support requests, prevent misuse, secure the service, maintain records, improve reliability and comply with legal obligations.</p>

        <h3>4. Who information may be disclosed to</h3>
        <p>We may use service providers that process information on our behalf, including Stripe for payments and billing, Vercel for application hosting, and Neon for database hosting. If you choose to open a Google Maps search, your browser connects to Google and that interaction is subject to Google’s own terms and privacy practices. We may also disclose information where required by law or reasonably necessary to protect legal rights, users or the service.</p>

        <h3>5. Overseas processing</h3>
        <p>Some service providers operate internationally. Personal information may therefore be processed or stored outside Australia, including in the United States and other locations used by those providers. We will review provider locations and privacy arrangements as the service changes.</p>

        <h3>6. Direct marketing</h3>
        <p>We will not use a purchase alone as consent for unrelated marketing messages. If we send commercial electronic messages, we will use consent where required, identify the sender and provide a functional way to unsubscribe.</p>

        <h3>7. Security</h3>
        <p>We use measures designed to reduce unauthorised access, including server-only secrets, signed Stripe webhooks, bounded database queries and not storing full card numbers. No online system can guarantee absolute security. We maintain a data-breach response process and will make notifications required by applicable law.</p>

        <h3>8. Retention</h3>
        <p>We keep information only for as long as reasonably needed for the purposes described above, to provide the service, resolve disputes, meet legal/accounting obligations and maintain security records. Payment and transaction records may need to be kept even after a trip or membership is deleted.</p>

        <h3>9. Access and correction</h3>
        <p>You may ask what personal information we hold about you or request correction by emailing <a href="mailto:tracey@genevieveapp.com.au">tracey@genevieveapp.com.au</a>. We may need to verify your identity before releasing or changing information.</p>

        <h3>10. Privacy complaints</h3>
        <p>Send privacy concerns to <a href="mailto:tracey@genevieveapp.com.au">tracey@genevieveapp.com.au</a> or PO Box 475, Labrador QLD 4215, Australia. We will investigate and respond within a reasonable time. If an Australian privacy regulator has jurisdiction and you remain dissatisfied, you may also have a right to raise the matter with that regulator.</p>

        <h3>11. Changes to this policy</h3>
        <p>We will update this policy when our information practices materially change and will update the date shown above. New data collection will not be hidden behind unrelated wording.</p>
      </article>
    </Shell>
  );
}
